### ISSUE TITLE
PhD defense about code and society issues

### ISSUE THREAD

**Issue by jibe-b** [promethe42/cocorico#108]
This could interest you: Paris Mo 28 november 2016

http://www.mines-paristech.fr/Formation/Doctorat/Soutenances-a-venir/Detail/Kseniia-ERMOSHINA/52368

**Comment by JMLX42** [comment]
Nice! Is that your thesis? Does it talk about Cocorico?

**Comment by jibe-b** [comment]
Not mine and not about Cocorico but a \<keywords\> high intensity high value open science/access crypto society issues civic tech\</keywords\> PhD work.
\<invitation\>Worth being there!\</invitation\>
