### ISSUE TITLE
Login/password on the VM

### ISSUE THREAD

**Issue by uhqd** [promethe42/cocorico#109]
Ok sorry I am just a physicist and I am not exactly a geek.
Well I am interested to test/modify "cocorico" 
I follow the install guidelines and  I am ok (install VirtualBox, Vagrant, editing /etc/hosts, 
Now I want to start building the project 
But what  should I use as login/password in the Ubuntu VM at opening (I work on Mac OS 10.10.5)
Thank you for help (of course I tried my login/PW of my mac session...).

**Comment by JMLX42** [comment]
The VM login/password is vagrant/vagrant. But you should **not** use ssh directly. Instead, you should  use `vagrant ssh {machineName}` to connect to the {machineName} VM.

For example:

```bash
vagrant ssh local
```

to connect to the machine named "local" (the local dev environment)
"local" is the default machine, so you can also just type `vagrant ssh` (without specifying the machine name).

More here:

https://www.vagrantup.com/docs/cli/ssh.html

**Comment by uhqd** [comment]
Thx. I try that.
