### ISSUE TITLE
Queue consumers do not reconnect when queue broker is restarted

### ISSUE THREAD

**Issue by YoannAubineau** [promethe42/cocorico#53]
The vote, ballot and webhook workers all connect to RabbitMQ at startup. However, when RabbitMQ is restarted, they do not reconnect by themselves. To have them continue consuming messages from the broker, they have to be restarted intentionally.

I can think of at least two potential solutions to this problem:
1. Automatically restart the 3 workers when RabbitMQ is restarted — provided message processing is reentrant (which, if it is not the case, is another kind of problem).
2. Have the 3 workers reconnect by themselves when the connection to RabbitMQ is lost. Such code should be shared between workers (as a base class, for example).

**Comment by JMLX42** [comment]
I would expect `forever` to do that already. Does it always happen or only when you run the services manually with `npm start`?

**Comment by YoannAubineau** [comment]
Unfortunately, `forever` does not help here. When the connection is dropped, neither the worker nor `forever` tries to recover from the situation. Same thing if RabbitMQ is down when the worker is started: the worker fails and nothing more happens next.

I guess the solution is to listen to 'close' events, both on the connection and channel objects, and exit with a non-zero error code for `forever` to restart the worker.

**Comment by JMLX42** [comment]
When the connection is dropped I would expect the process to - at least - end. It doesn't ?

**Comment by YoannAubineau** [comment]
No, when the connection to RabbitMQ is dropped, the worker does not exit. For the worker to exit, we have to listen to 'close' events from connection and channel objects and act accordingly.

Fortunately, I have found this additional library that, apparently, does the job for us already:

https://github.com/shyiko/amqplib-auto-recovery/search?utf8=%E2%9C%93&q=on%28%27close%27%29

**Comment by JMLX42** [comment]
Related to #62

**Comment by YoannAubineau** [comment]
Not sure it is fixed. Have you tested?

**Comment by JMLX42** [comment]
Yes. The trick is to make sure the process exits when there is an error.
The master process (or forever) will retart it.

Please test it to proof it.
