### ISSUE TITLE
Implement a vote.question in /api/vote to be able to embed a question with the vote

### ISSUE THREAD

**Issue by thibauld** [promethe42/cocorico#79]
Typically, in the following examle, I should be able to ask the following question/sentence above the labels : "Pour présider la France, ayant pris tous les éléments en compte, je juge en conscience que ce candidat serait"

![missing-question](https://cloud.githubusercontent.com/assets/197119/19564432/90d48b16-96b1-11e6-8c66-a538dc676d1d.png)

**Comment by JMLX42** [comment]
Fixed in 5139b4ec0c3a663bbef0a5eefcdd88a10667db5c
