### ISSUE TITLE
Allow the UI locale to be specified (forced) at vote creation

### ISSUE THREAD

**Issue by thibauld** [promethe42/cocorico#82]
Today the locale in which the text is displayed is being automatically selected depending on the user's browser locale configuration. Given that (i) labels and messages are not localized and (ii) multi-language voting is very likely a rare case (by default english will be used), it would be good to be able to force the use of a specific locale at vote creation time (/api/vote). I would add 'locale' as an optional parameter.

**Comment by JMLX42** [comment]
You can force the locale using the "lang" GET parameter. See a14155cf001a71ac4091fb8baadd38161379c689
