### ISSUE TITLE
iframe postMessage data should include the value of the vote id

### ISSUE THREAD

**Issue by thibauld** [promethe42/cocorico#83]
I use several cocorico iframe on one page. Each of these iframe emit messages with postMessage but I am unable to trace back which iFrame emitted which message if the message does not include the id of the vote (1 vote <-> 1 iframe). Unless I am mistaken, I did not see the id of the vote in the voteComplete nor voteSuccess MessageEvents.

![image](https://cloud.githubusercontent.com/assets/197119/19586048/7ee25578-971f-11e6-857c-4230eb8f2add.png)

My first idea would be to pass voteComplete_[voteId] as data but I am definitely not a JS expert :)

**Comment by JMLX42** [comment]
You can use the URL in `e.currentTarget.window.document.location` to get the vote id:

``` javascript
window.addEventListener('message', function(e) {
  var voteId = e.currentTarget.window.document.location.pathname.split('/')[3];

  // ...
});
```
