### ISSUE TITLE
LaPrimaire.org vote label typo

### ISSUE THREAD

**Issue by d-j-n** [promethe42/cocorico#90]
There is a typo in one of the vote labels which is written "tres bien" instead of "très bien".

**Edit** : translated from French from the original message below

> Il manque un accent grave au vote "tres bien", qui devrait être écrit "très bien".

**Comment by JMLX42** [comment]
Vote labels are set by the 3rd party application (in this case I'm suspecting you're talking about LaPrimaire.org). So this bug report should be made to the faulty app.
